export { default as electron } from './electron.mjs'
export { default as nest } from './nest.mjs'
export { default as next } from './next.mjs'
export { default as nextJs } from './next-js.mjs'
export { default as normal } from './normal.mjs'
export { default as nuxt } from './nuxt.mjs'
export { default as umi } from './umi.mjs'
